/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    services: Service;
    leads: Lead;
    programs: Program;
    'legal-pages': LegalPage;
    reviews: Review;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    programs: ProgramsSelect<false> | ProgramsSelect<true>;
    'legal-pages': LegalPagesSelect<false> | LegalPagesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
    home: Home;
    about: About;
    contacts: Contact;
    'programs-section': ProgramsSection;
    its: It;
    fresh: Fresh;
    grm: Grm;
    'fresh-vs-grm': FreshVsGrm;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    contacts: ContactsSelect<false> | ContactsSelect<true>;
    'programs-section': ProgramsSectionSelect<false> | ProgramsSectionSelect<true>;
    its: ItsSelect<false> | ItsSelect<true>;
    fresh: FreshSelect<false> | FreshSelect<true>;
    grm: GrmSelect<false> | GrmSelect<true>;
    'fresh-vs-grm': FreshVsGrmSelect<false> | FreshVsGrmSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Латиницей, через дефис: otchetnost-i-nalogi
   */
  slug: string;
  icon:
    | 'report'
    | 'calculator'
    | 'signature'
    | 'receipt'
    | 'book'
    | 'folder'
    | 'print'
    | 'assignment'
    | 'exchange'
    | 'sync'
    | 'network'
    | 'globe'
    | 'cloud'
    | 'server'
    | 'database'
    | 'mobile'
    | 'devices'
    | 'extension'
    | 'phone'
    | 'email'
    | 'clock'
    | 'calendar'
    | 'location'
    | 'chat'
    | 'mic'
    | 'video'
    | 'headset'
    | 'wallet'
    | 'bank'
    | 'ruble'
    | 'cart'
    | 'cash-register'
    | 'barcode'
    | 'scan'
    | 'storefront'
    | 'no-cost'
    | 'truck'
    | 'warehouse'
    | 'package'
    | 'plane'
    | 'users'
    | 'handshake'
    | 'education'
    | 'certificate'
    | 'health'
    | 'company'
    | 'badge'
    | 'shield'
    | 'lock'
    | 'key'
    | 'check'
    | 'star'
    | 'sparkle'
    | 'bolt'
    | 'rocket'
    | 'idea'
    | 'timer'
    | 'chart'
    | 'bar-chart'
    | 'gear'
    | 'tools'
    | 'search'
    | 'plus'
    | 'edit';
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug: string;
  /**
   * Крупный текст в карточке. Тире — длинное «—»
   */
  headline: string;
  /**
   * До 130 символов
   */
  description: string;
  category: number | Category;
  icon:
    | 'report'
    | 'calculator'
    | 'signature'
    | 'receipt'
    | 'book'
    | 'folder'
    | 'print'
    | 'assignment'
    | 'exchange'
    | 'sync'
    | 'network'
    | 'globe'
    | 'cloud'
    | 'server'
    | 'database'
    | 'mobile'
    | 'devices'
    | 'extension'
    | 'phone'
    | 'email'
    | 'clock'
    | 'calendar'
    | 'location'
    | 'chat'
    | 'mic'
    | 'video'
    | 'headset'
    | 'wallet'
    | 'bank'
    | 'ruble'
    | 'cart'
    | 'cash-register'
    | 'barcode'
    | 'scan'
    | 'storefront'
    | 'no-cost'
    | 'truck'
    | 'warehouse'
    | 'package'
    | 'plane'
    | 'users'
    | 'handshake'
    | 'education'
    | 'certificate'
    | 'health'
    | 'company'
    | 'badge'
    | 'shield'
    | 'lock'
    | 'key'
    | 'check'
    | 'star'
    | 'sparkle'
    | 'bolt'
    | 'rocket'
    | 'idea'
    | 'timer'
    | 'chart'
    | 'bar-chart'
    | 'gear'
    | 'tools'
    | 'search'
    | 'plus'
    | 'edit';
  isPopular?: boolean | null;
  isNew?: boolean | null;
  /**
   * Карточка останется в CMS, но не будет показана на сайте
   */
  isHidden?: boolean | null;
  related?: (number | Service)[] | null;
  popup?: {
    whoNeedsIt?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Пусто — блок не рендерится. Шаги не выдумывать
     */
    howItWorks?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    requirements?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    ctaText?: string | null;
  };
  sourceUrls?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  phone: string;
  email: string;
  comment?: string | null;
  status: 'new' | 'in_progress' | 'closed';
  /**
   * Откуда отправлена заявка
   */
  page?: string | null;
  consentAt?: string | null;
  consentIp?: string | null;
  consentVersion?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs".
 */
export interface Program {
  id: number;
  title: string;
  /**
   * Адрес страницы: /programs/слаг
   */
  slug: string;
  /**
   * В табах текст короче, чем в заголовке
   */
  tabLabel: string;
  /**
   * Порядок вкладок слева направо
   */
  order: number;
  lead: string;
  /**
   * Название программы. Выводится полужирным
   */
  bodyStrong: string;
  /**
   * Идёт сразу после выделенного начала, в том же абзаце
   */
  bodyIntro: string;
  /**
   * Абзацы разделяются переводом строки
   */
  body: string;
  ctaText?: string | null;
  shortFacts?: {
    items?:
      | {
          fact: string;
          /**
           * Не длиннее 5 слов
           */
          caption: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Продолжение фразы «Подходит: …»
     */
    suits?: string | null;
  };
  /**
   * Без двоеточия в конце
   */
  cardsTitle?: string | null;
  cardsLayout?: ('icon' | 'title' | 'icon-title') | null;
  /**
   * Пустой список — блок карточек не выводится на сайте
   */
  cards?:
    | {
        icon?:
          | (
              | 'report'
              | 'calculator'
              | 'signature'
              | 'receipt'
              | 'book'
              | 'folder'
              | 'print'
              | 'assignment'
              | 'exchange'
              | 'sync'
              | 'network'
              | 'globe'
              | 'cloud'
              | 'server'
              | 'database'
              | 'mobile'
              | 'devices'
              | 'extension'
              | 'phone'
              | 'email'
              | 'clock'
              | 'calendar'
              | 'location'
              | 'chat'
              | 'mic'
              | 'video'
              | 'headset'
              | 'wallet'
              | 'bank'
              | 'ruble'
              | 'cart'
              | 'cash-register'
              | 'barcode'
              | 'scan'
              | 'storefront'
              | 'no-cost'
              | 'truck'
              | 'warehouse'
              | 'package'
              | 'plane'
              | 'users'
              | 'handshake'
              | 'education'
              | 'certificate'
              | 'health'
              | 'company'
              | 'badge'
              | 'shield'
              | 'lock'
              | 'key'
              | 'check'
              | 'star'
              | 'sparkle'
              | 'bolt'
              | 'rocket'
              | 'idea'
              | 'timer'
              | 'chart'
              | 'bar-chart'
              | 'gear'
              | 'tools'
              | 'search'
              | 'plus'
              | 'edit'
            )
          | null;
        title?: string | null;
        text: string;
        list?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  hasTable?: boolean | null;
  table?: {
    title?: string | null;
    /**
     * «Возможности», «По подсистемам», «Сервисы ИТС»
     */
    firstColumnLabel?: string | null;
    col1Label?: string | null;
    col2Label?: string | null;
    /**
     * Пусто — колонка не выводится
     */
    col3Label?: string | null;
    rows?:
      | {
          label: string;
          col1?: ('yes' | 'no' | 'text') | null;
          col2?: ('yes' | 'no' | 'text') | null;
          col3?: ('yes' | 'no' | 'text') | null;
          col1Text?: string | null;
          col2Text?: string | null;
          col3Text?: string | null;
          id?: string | null;
        }[]
      | null;
    hasDetails?: boolean | null;
    detailsLabel?: string | null;
    detailsRows?:
      | {
          label: string;
          col1?: ('yes' | 'no' | 'text') | null;
          col2?: ('yes' | 'no' | 'text') | null;
          col3?: ('yes' | 'no' | 'text') | null;
          col1Text?: string | null;
          col2Text?: string | null;
          col3Text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages".
 */
export interface LegalPage {
  id: number;
  slug: 'privacy' | 'cookie' | 'consent';
  title: string;
  /**
   * Необязательный
   */
  lead?: string | null;
  /**
   * Показывается на странице. Обязательный реквизит документа
   */
  effectiveDate: string;
  /**
   * Пишется в каждую заявку. Менять при любой правке текста, иначе в базе останется ссылка на редакцию, которой человек не видел. Формат — дата: 2026-09-05
   */
  version?: string | null;
  sections: {
    /**
     * Номер раздела пишется прямо в заголовке («1. Общие положения»). Автонумерации нет намеренно: на пункты юридического документа ссылаются по номерам, и сдвиг после удаления раздела ломал бы ссылки
     */
    heading?: string | null;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Нумерацию рисует браузер. Для сквозных пунктов вида «3.2» — абзацы
     */
    listType?: ('unordered' | 'ordered') | null;
    list?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  author: string;
  /**
   * Например: руководитель, бухгалтерская компания «Актив Учёт»
   */
  role: string;
  /**
   * Кавычки-ёлочки ставит вёрстка — в поле их писать не нужно
   */
  text: string;
  /**
   * На главной выводятся три первых по порядку
   */
  showOnHome?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'programs';
        value: number | Program;
      } | null)
    | ({
        relationTo: 'legal-pages';
        value: number | LegalPage;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  icon?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  headline?: T;
  description?: T;
  category?: T;
  icon?: T;
  isPopular?: T;
  isNew?: T;
  isHidden?: T;
  related?: T;
  popup?:
    | T
    | {
        whoNeedsIt?:
          | T
          | {
              text?: T;
              id?: T;
            };
        howItWorks?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        requirements?:
          | T
          | {
              text?: T;
              id?: T;
            };
        ctaText?: T;
      };
  sourceUrls?:
    | T
    | {
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  comment?: T;
  status?: T;
  page?: T;
  consentAt?: T;
  consentIp?: T;
  consentVersion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs_select".
 */
export interface ProgramsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  tabLabel?: T;
  order?: T;
  lead?: T;
  bodyStrong?: T;
  bodyIntro?: T;
  body?: T;
  ctaText?: T;
  shortFacts?:
    | T
    | {
        items?:
          | T
          | {
              fact?: T;
              caption?: T;
              id?: T;
            };
        suits?: T;
      };
  cardsTitle?: T;
  cardsLayout?: T;
  cards?:
    | T
    | {
        icon?: T;
        title?: T;
        text?: T;
        list?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  hasTable?: T;
  table?:
    | T
    | {
        title?: T;
        firstColumnLabel?: T;
        col1Label?: T;
        col2Label?: T;
        col3Label?: T;
        rows?:
          | T
          | {
              label?: T;
              col1?: T;
              col2?: T;
              col3?: T;
              col1Text?: T;
              col2Text?: T;
              col3Text?: T;
              id?: T;
            };
        hasDetails?: T;
        detailsLabel?: T;
        detailsRows?:
          | T
          | {
              label?: T;
              col1?: T;
              col2?: T;
              col3?: T;
              col1Text?: T;
              col2Text?: T;
              col3Text?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  lead?: T;
  effectiveDate?: T;
  version?: T;
  sections?:
    | T
    | {
        heading?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        listType?: T;
        list?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  author?: T;
  role?: T;
  text?: T;
  showOnHome?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * В том виде, в каком показывается на сайте
   */
  phone: string;
  /**
   * Заполняется автоматически из поля слева
   */
  phoneRaw?: string | null;
  email: string;
  address: string;
  workHours: string;
  legalName: string;
  inn: string;
  /**
   * Уточнить у Дмитрия
   */
  ogrn?: string | null;
  /**
   * Один текст на все страницы с тарифами: программы, ИТС, Фреш. Живёт здесь, а не в разделе «Программы 1С», потому что правка должна гасить кеш всего сайта — Settings это и делает.
   */
  tariffDisclaimer: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  hero: {
    title: string;
    lead: string;
    ctaText?: string | null;
  };
  states: {
    title: string;
    lead?: string | null;
    openLabel?: string | null;
    closeLabel?: string | null;
    criteriaTitle?: string | null;
    solutionLabel?: string | null;
    items?:
      | {
          title: string;
          /**
           * Одна строка — в свёрнутом виде места больше нет
           */
          description: string;
          criteria?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          solutions?:
            | {
                /**
                 * Условие выбора: «База без доработок», «Своего специалиста нет». Капс делает вёрстка
                 */
                eyebrow: string;
                title: string;
                text: string;
                /**
                 * Внутренний путь: /fresh, /programs, /services
                 */
                href: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    footer: {
      text: string;
      buttonLabel?: string | null;
    };
  };
  directions: {
    title: string;
    items?:
      | {
          icon?:
            | (
                | 'report'
                | 'calculator'
                | 'signature'
                | 'receipt'
                | 'book'
                | 'folder'
                | 'print'
                | 'assignment'
                | 'exchange'
                | 'sync'
                | 'network'
                | 'globe'
                | 'cloud'
                | 'server'
                | 'database'
                | 'mobile'
                | 'devices'
                | 'extension'
                | 'phone'
                | 'email'
                | 'clock'
                | 'calendar'
                | 'location'
                | 'chat'
                | 'mic'
                | 'video'
                | 'headset'
                | 'wallet'
                | 'bank'
                | 'ruble'
                | 'cart'
                | 'cash-register'
                | 'barcode'
                | 'scan'
                | 'storefront'
                | 'no-cost'
                | 'truck'
                | 'warehouse'
                | 'package'
                | 'plane'
                | 'users'
                | 'handshake'
                | 'education'
                | 'certificate'
                | 'health'
                | 'company'
                | 'badge'
                | 'shield'
                | 'lock'
                | 'key'
                | 'check'
                | 'star'
                | 'sparkle'
                | 'bolt'
                | 'rocket'
                | 'idea'
                | 'timer'
                | 'chart'
                | 'bar-chart'
                | 'gear'
                | 'tools'
                | 'search'
                | 'plus'
                | 'edit'
              )
            | null;
          title: string;
          /**
           * Оранжевая строка под названием
           */
          lead: string;
          list?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          href: string;
          buttonLabel?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Карточки берутся из каталога — сервисы с флагом «Популярное». Здесь только обрамление блока
   */
  servicesPreview: {
    title: string;
    buttonLabel?: string | null;
    /**
     * Видна скринридеру, глазами — только стрелка
     */
    allLabel?: string | null;
  };
  company: {
    title: string;
    lead?: string | null;
    buttonLabel?: string | null;
    buttonHref?: string | null;
    counters?:
      | {
          value: string;
          caption: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Выводится тем же компонентом, что и пункты 01–06 на /its
   */
  afterPayment: {
    title: string;
    lead?: string | null;
    /**
     * Номера рисуются порядком, отдельного поля у шага нет
     */
    items?:
      | {
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  faq: {
    title: string;
    items?:
      | {
          question: string;
          /**
           * Абзацы разделяются переводом строки
           */
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  title: string;
  /**
   * Абзацы разделяются переводом строки
   */
  body: string;
  /**
   * Необязательно. Пока не загружено — на месте фото серая плашка
   */
  photo?: (number | null) | Media;
  /**
   * Четыре в макете. Порядок — как в списке
   */
  counters?:
    | {
        /**
         * Например: 20+, 2014, 1200+
         */
        value: string;
        caption: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Без двоеточия в конце
   */
  reviewsTitle?: string | null;
  /**
   * Сами отзывы правятся в разделе «Отзывы». Здесь только текст над ними. На эту страницу идут все отзывы, на главную — три с галочкой «Показывать на главной»
   */
  reviewsLead?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts".
 */
export interface Contact {
  id: number;
  title: string;
  lead: string;
  phone: {
    label: string;
    /**
     * Необязательно. Само значение берётся из «Реквизиты и контакты»
     */
    caption?: string | null;
  };
  email: {
    label: string;
    /**
     * Необязательно. Само значение берётся из «Реквизиты и контакты»
     */
    caption?: string | null;
  };
  hours: {
    label: string;
    /**
     * Необязательно. Само значение берётся из «Реквизиты и контакты»
     */
    caption?: string | null;
  };
  address: {
    label: string;
    /**
     * Необязательно. Само значение берётся из «Реквизиты и контакты»
     */
    caption?: string | null;
  };
  legal: {
    label: string;
    /**
     * Необязательно. Само значение берётся из «Реквизиты и контакты»
     */
    caption?: string | null;
  };
  inn: {
    label: string;
    /**
     * Необязательно. Само значение берётся из «Реквизиты и контакты»
     */
    caption?: string | null;
  };
  map: {
    /**
     * Адрес виджета из конструктора Яндекс.Карт. Значение по умолчанию ищет офис по адресу; если метка встала неточно, соберите карту в конструкторе и вставьте её ссылку сюда. Параметр lang=ru_RU обязателен: подписи на карте должны быть на русском.
     */
    url: string;
    /**
     * Тёмная подпись в углу карты
     */
    plaque?: string | null;
    buttonLabel?: string | null;
    /**
     * Показывается до нажатия на кнопку. Пока карта не загружена, к Яндексу не уходит ни одного запроса
     */
    note?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs-section".
 */
export interface ProgramsSection {
  id: number;
  title: string;
  lead: string;
  cloudBanner: {
    title: string;
    text: string;
    buttons?:
      | {
          label: string;
          href: string;
          style?: ('primary' | 'accent') | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "its".
 */
export interface It {
  id: number;
  title: string;
  /**
   * Не дублировать лид каталога сервисов
   */
  lead: string;
  /**
   * Выводится полужирным, в том же абзаце
   */
  bodyStrong: string;
  bodyIntro: string;
  /**
   * Абзацы разделяются переводом строки
   */
  body: string;
  ctaText?: string | null;
  shortFacts?: {
    items?:
      | {
          fact: string;
          caption: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Продолжение фразы «Подходит: …»
     */
    suits?: string | null;
  };
  /**
   * Без двоеточия в конце
   */
  cardsTitle?: string | null;
  /**
   * Раскладка всегда «иконка, заголовок и текст»
   */
  cards?:
    | {
        icon:
          | 'report'
          | 'calculator'
          | 'signature'
          | 'receipt'
          | 'book'
          | 'folder'
          | 'print'
          | 'assignment'
          | 'exchange'
          | 'sync'
          | 'network'
          | 'globe'
          | 'cloud'
          | 'server'
          | 'database'
          | 'mobile'
          | 'devices'
          | 'extension'
          | 'phone'
          | 'email'
          | 'clock'
          | 'calendar'
          | 'location'
          | 'chat'
          | 'mic'
          | 'video'
          | 'headset'
          | 'wallet'
          | 'bank'
          | 'ruble'
          | 'cart'
          | 'cash-register'
          | 'barcode'
          | 'scan'
          | 'storefront'
          | 'no-cost'
          | 'truck'
          | 'warehouse'
          | 'package'
          | 'plane'
          | 'users'
          | 'handshake'
          | 'education'
          | 'certificate'
          | 'health'
          | 'company'
          | 'badge'
          | 'shield'
          | 'lock'
          | 'key'
          | 'check'
          | 'star'
          | 'sparkle'
          | 'bolt'
          | 'rocket'
          | 'idea'
          | 'timer'
          | 'chart'
          | 'bar-chart'
          | 'gear'
          | 'tools'
          | 'search'
          | 'plus'
          | 'edit';
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  included: {
    title: string;
    /**
     * Номера 01, 02, 03 рисуются индексом — в тексте их писать не надо
     */
    items?:
      | {
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  table?: {
    title?: string | null;
    firstColumnLabel?: string | null;
    col1Label?: string | null;
    col2Label?: string | null;
    rows?:
      | {
          label: string;
          /**
           * Если выбран — строка становится ссылкой и открывает попап сервиса. Пусто — обычный текст
           */
          service?: (number | null) | Service;
          /**
           * Например /fresh. Заполняется, только если сервис каталога не выбран
           */
          href?: string | null;
          col1?: ('yes' | 'no' | 'text') | null;
          col2?: ('yes' | 'no' | 'text') | null;
          col3?: ('yes' | 'no' | 'text') | null;
          col1Text?: string | null;
          col2Text?: string | null;
          col3Text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  ctaBanner: {
    title: string;
    text: string;
    buttonLabel: string;
    buttonHref: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fresh".
 */
export interface Fresh {
  id: number;
  title: string;
  lead: string;
  /**
   * Выводится полужирным, в том же абзаце
   */
  bodyStrong: string;
  bodyIntro: string;
  /**
   * Абзацы разделяются переводом строки
   */
  body: string;
  ctaText?: string | null;
  shortFacts?: {
    items?:
      | {
          fact: string;
          caption: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Продолжение фразы «Подходит: …»
     */
    suits?: string | null;
  };
  /**
   * Без двоеточия в конце
   */
  cardsTitle?: string | null;
  /**
   * Раскладка всегда «иконка и текст», без заголовков
   */
  cards?:
    | {
        icon?:
          | (
              | 'report'
              | 'calculator'
              | 'signature'
              | 'receipt'
              | 'book'
              | 'folder'
              | 'print'
              | 'assignment'
              | 'exchange'
              | 'sync'
              | 'network'
              | 'globe'
              | 'cloud'
              | 'server'
              | 'database'
              | 'mobile'
              | 'devices'
              | 'extension'
              | 'phone'
              | 'email'
              | 'clock'
              | 'calendar'
              | 'location'
              | 'chat'
              | 'mic'
              | 'video'
              | 'headset'
              | 'wallet'
              | 'bank'
              | 'ruble'
              | 'cart'
              | 'cash-register'
              | 'barcode'
              | 'scan'
              | 'storefront'
              | 'no-cost'
              | 'truck'
              | 'warehouse'
              | 'package'
              | 'plane'
              | 'users'
              | 'handshake'
              | 'education'
              | 'certificate'
              | 'health'
              | 'company'
              | 'badge'
              | 'shield'
              | 'lock'
              | 'key'
              | 'check'
              | 'star'
              | 'sparkle'
              | 'bolt'
              | 'rocket'
              | 'idea'
              | 'timer'
              | 'chart'
              | 'bar-chart'
              | 'gear'
              | 'tools'
              | 'search'
              | 'plus'
              | 'edit'
            )
          | null;
        text: string;
        list?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  tariffs: {
    title: string;
    lead: string;
    /**
     * Ровно два: Базовый и ПРОФ. Остальные три — в раскрывашке ниже
     */
    cards?:
      | {
          name: string;
          /**
           * Например «Рекомендуем». Необязательный
           */
          badge?: string | null;
          whoFits: string;
          seats: string;
          seatsLabel: string;
          bases: string;
          basesLabel: string;
          items?:
            | {
                kind: 'check' | 'note';
                text: string;
                list?:
                  | {
                      text: string;
                      id?: string | null;
                    }[]
                  | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    extra: {
      title: string;
      items?:
        | {
            name: string;
            specs: string;
            text: string;
            /**
             * Кому нужен тариф. Выводится курсивом
             */
            note?: string | null;
            id?: string | null;
          }[]
        | null;
      banner: {
        text: string;
        buttonLabel: string;
      };
    };
    common: {
      title: string;
      /**
       * Четыре в ряд. Пятая уедет на вторую строку и поломает ритм
       */
      items?:
        | {
            icon?:
              | (
                  | 'report'
                  | 'calculator'
                  | 'signature'
                  | 'receipt'
                  | 'book'
                  | 'folder'
                  | 'print'
                  | 'assignment'
                  | 'exchange'
                  | 'sync'
                  | 'network'
                  | 'globe'
                  | 'cloud'
                  | 'server'
                  | 'database'
                  | 'mobile'
                  | 'devices'
                  | 'extension'
                  | 'phone'
                  | 'email'
                  | 'clock'
                  | 'calendar'
                  | 'location'
                  | 'chat'
                  | 'mic'
                  | 'video'
                  | 'headset'
                  | 'wallet'
                  | 'bank'
                  | 'ruble'
                  | 'cart'
                  | 'cash-register'
                  | 'barcode'
                  | 'scan'
                  | 'storefront'
                  | 'no-cost'
                  | 'truck'
                  | 'warehouse'
                  | 'package'
                  | 'plane'
                  | 'users'
                  | 'handshake'
                  | 'education'
                  | 'certificate'
                  | 'health'
                  | 'company'
                  | 'badge'
                  | 'shield'
                  | 'lock'
                  | 'key'
                  | 'check'
                  | 'star'
                  | 'sparkle'
                  | 'bolt'
                  | 'rocket'
                  | 'idea'
                  | 'timer'
                  | 'chart'
                  | 'bar-chart'
                  | 'gear'
                  | 'tools'
                  | 'search'
                  | 'plus'
                  | 'edit'
                )
              | null;
            title: string;
            text: string;
            id?: string | null;
          }[]
        | null;
    };
    switchNote: {
      title: string;
      text: string;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grm".
 */
export interface Grm {
  id: number;
  title: string;
  lead: string;
  /**
   * Выводится полужирным, в том же абзаце
   */
  bodyStrong: string;
  bodyIntro: string;
  /**
   * Необязательно. Абзацы разделяются переводом строки
   */
  body?: string | null;
  ctaText?: string | null;
  shortFacts?: {
    items?:
      | {
          fact: string;
          caption: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Продолжение фразы «Подходит: …»
     */
    suits?: string | null;
  };
  /**
   * Без двоеточия в конце
   */
  cardsTitle?: string | null;
  /**
   * Необязательный. Вводит список карточек
   */
  cardsLead?: string | null;
  /**
   * Раскладка всегда «иконка и текст», без заголовков
   */
  cards?:
    | {
        icon?:
          | (
              | 'report'
              | 'calculator'
              | 'signature'
              | 'receipt'
              | 'book'
              | 'folder'
              | 'print'
              | 'assignment'
              | 'exchange'
              | 'sync'
              | 'network'
              | 'globe'
              | 'cloud'
              | 'server'
              | 'database'
              | 'mobile'
              | 'devices'
              | 'extension'
              | 'phone'
              | 'email'
              | 'clock'
              | 'calendar'
              | 'location'
              | 'chat'
              | 'mic'
              | 'video'
              | 'headset'
              | 'wallet'
              | 'bank'
              | 'ruble'
              | 'cart'
              | 'cash-register'
              | 'barcode'
              | 'scan'
              | 'storefront'
              | 'no-cost'
              | 'truck'
              | 'warehouse'
              | 'package'
              | 'plane'
              | 'users'
              | 'handshake'
              | 'education'
              | 'certificate'
              | 'health'
              | 'company'
              | 'badge'
              | 'shield'
              | 'lock'
              | 'key'
              | 'check'
              | 'star'
              | 'sparkle'
              | 'bolt'
              | 'rocket'
              | 'idea'
              | 'timer'
              | 'chart'
              | 'bar-chart'
              | 'gear'
              | 'tools'
              | 'search'
              | 'plus'
              | 'edit'
            )
          | null;
        text: string;
        list?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fresh-vs-grm".
 */
export interface FreshVsGrm {
  id: number;
  title: string;
  lead: string;
  fresh: {
    title: string;
    /**
     * Необязательный. Капс делает вёрстка — писать обычным регистром
     */
    badge?: string | null;
    description: string;
    /**
     * Названия параметров должны совпадать в обеих колонках — иначе строки не встанут друг напротив друга
     */
    rows?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Необязательная. Мелкий серый текст в самом низу колонки
     */
    note?: string | null;
    /**
     * Ссылка прячется на той странице, где эта колонка и так открыта
     */
    href: string;
  };
  grm: {
    title: string;
    /**
     * Необязательный. Капс делает вёрстка — писать обычным регистром
     */
    badge?: string | null;
    description: string;
    /**
     * Названия параметров должны совпадать в обеих колонках — иначе строки не встанут друг напротив друга
     */
    rows?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Необязательная. Мелкий серый текст в самом низу колонки
     */
    note?: string | null;
    /**
     * Ссылка прячется на той странице, где эта колонка и так открыта
     */
    href: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  phone?: T;
  phoneRaw?: T;
  email?: T;
  address?: T;
  workHours?: T;
  legalName?: T;
  inn?: T;
  ogrn?: T;
  tariffDisclaimer?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        lead?: T;
        ctaText?: T;
      };
  states?:
    | T
    | {
        title?: T;
        lead?: T;
        openLabel?: T;
        closeLabel?: T;
        criteriaTitle?: T;
        solutionLabel?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              criteria?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              solutions?:
                | T
                | {
                    eyebrow?: T;
                    title?: T;
                    text?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
            };
        footer?:
          | T
          | {
              text?: T;
              buttonLabel?: T;
            };
      };
  directions?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              lead?: T;
              list?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              href?: T;
              buttonLabel?: T;
              id?: T;
            };
      };
  servicesPreview?:
    | T
    | {
        title?: T;
        buttonLabel?: T;
        allLabel?: T;
      };
  company?:
    | T
    | {
        title?: T;
        lead?: T;
        buttonLabel?: T;
        buttonHref?: T;
        counters?:
          | T
          | {
              value?: T;
              caption?: T;
              id?: T;
            };
      };
  afterPayment?:
    | T
    | {
        title?: T;
        lead?: T;
        items?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
      };
  faq?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  photo?: T;
  counters?:
    | T
    | {
        value?: T;
        caption?: T;
        id?: T;
      };
  reviewsTitle?: T;
  reviewsLead?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts_select".
 */
export interface ContactsSelect<T extends boolean = true> {
  title?: T;
  lead?: T;
  phone?:
    | T
    | {
        label?: T;
        caption?: T;
      };
  email?:
    | T
    | {
        label?: T;
        caption?: T;
      };
  hours?:
    | T
    | {
        label?: T;
        caption?: T;
      };
  address?:
    | T
    | {
        label?: T;
        caption?: T;
      };
  legal?:
    | T
    | {
        label?: T;
        caption?: T;
      };
  inn?:
    | T
    | {
        label?: T;
        caption?: T;
      };
  map?:
    | T
    | {
        url?: T;
        plaque?: T;
        buttonLabel?: T;
        note?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs-section_select".
 */
export interface ProgramsSectionSelect<T extends boolean = true> {
  title?: T;
  lead?: T;
  cloudBanner?:
    | T
    | {
        title?: T;
        text?: T;
        buttons?:
          | T
          | {
              label?: T;
              href?: T;
              style?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "its_select".
 */
export interface ItsSelect<T extends boolean = true> {
  title?: T;
  lead?: T;
  bodyStrong?: T;
  bodyIntro?: T;
  body?: T;
  ctaText?: T;
  shortFacts?:
    | T
    | {
        items?:
          | T
          | {
              fact?: T;
              caption?: T;
              id?: T;
            };
        suits?: T;
      };
  cardsTitle?: T;
  cards?:
    | T
    | {
        icon?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  included?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
      };
  table?:
    | T
    | {
        title?: T;
        firstColumnLabel?: T;
        col1Label?: T;
        col2Label?: T;
        rows?:
          | T
          | {
              label?: T;
              service?: T;
              href?: T;
              col1?: T;
              col2?: T;
              col3?: T;
              col1Text?: T;
              col2Text?: T;
              col3Text?: T;
              id?: T;
            };
      };
  ctaBanner?:
    | T
    | {
        title?: T;
        text?: T;
        buttonLabel?: T;
        buttonHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fresh_select".
 */
export interface FreshSelect<T extends boolean = true> {
  title?: T;
  lead?: T;
  bodyStrong?: T;
  bodyIntro?: T;
  body?: T;
  ctaText?: T;
  shortFacts?:
    | T
    | {
        items?:
          | T
          | {
              fact?: T;
              caption?: T;
              id?: T;
            };
        suits?: T;
      };
  cardsTitle?: T;
  cards?:
    | T
    | {
        icon?: T;
        text?: T;
        list?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  tariffs?:
    | T
    | {
        title?: T;
        lead?: T;
        cards?:
          | T
          | {
              name?: T;
              badge?: T;
              whoFits?: T;
              seats?: T;
              seatsLabel?: T;
              bases?: T;
              basesLabel?: T;
              items?:
                | T
                | {
                    kind?: T;
                    text?: T;
                    list?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
            };
        extra?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    name?: T;
                    specs?: T;
                    text?: T;
                    note?: T;
                    id?: T;
                  };
              banner?:
                | T
                | {
                    text?: T;
                    buttonLabel?: T;
                  };
            };
        common?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    text?: T;
                    id?: T;
                  };
            };
        switchNote?:
          | T
          | {
              title?: T;
              text?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grm_select".
 */
export interface GrmSelect<T extends boolean = true> {
  title?: T;
  lead?: T;
  bodyStrong?: T;
  bodyIntro?: T;
  body?: T;
  ctaText?: T;
  shortFacts?:
    | T
    | {
        items?:
          | T
          | {
              fact?: T;
              caption?: T;
              id?: T;
            };
        suits?: T;
      };
  cardsTitle?: T;
  cardsLead?: T;
  cards?:
    | T
    | {
        icon?: T;
        text?: T;
        list?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fresh-vs-grm_select".
 */
export interface FreshVsGrmSelect<T extends boolean = true> {
  title?: T;
  lead?: T;
  fresh?:
    | T
    | {
        title?: T;
        badge?: T;
        description?: T;
        rows?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        note?: T;
        href?: T;
      };
  grm?:
    | T
    | {
        title?: T;
        badge?: T;
        description?: T;
        rows?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        note?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}